<a href="https://colab.research.google.com/github/ednavivianasegura/ERAP_CursoPython/blob/main/Modulo1_b/01.numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [1]:
import numpy as np

In [ ]:
lista = [1, 2, 3]

In [ ]:
type(lista)

In [ ]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [ ]:
vector = [-2, 4, 1, 3.5]

vector = np.array(vector)

vector

array([-2. ,  4. ,  1. ,  3.5])

In [ ]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

In [ ]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

In [ ]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(2, 2)

matriz_1

array([[-2. ,  4. ],
       [ 1. ,  3.5]])

In [ ]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .T

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[-2.   1. ]
 [ 4.   3.5]]
--------------------
[[-2.   1. ]
 [ 4.   3.5]]


In [ ]:
# .tolist() retorna el array en una lista

matriz_1.tolist()

[[-2.0, 1.0], [4.0, 3.5]]

In [ ]:
list(matriz_1)

[array([-2.,  4.]), array([1. , 3.5])]

In [ ]:
vector

In [ ]:
matriz_1

In [ ]:
# .flatten() retorna un vector plano con los elementos de la matriz

matriz_1.flatten()

In [ ]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

print("Antes de .sort()", vector)

vector.sort()

print("Después de .sort()", vector)

In [ ]:
vector

In [ ]:
# .ndim retorna el número de dimensiones

vector.ndim

In [ ]:
# .size retorna el número de elementos

vector.size

In [ ]:
# .shape retorna en una tupla las dimesiones de la matriz

matriz_1.shape

In [ ]:
# .dtype retorna el tipo de dato de los elementos de la matriz

vector.dtype

### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [ ]:
matriz = np.array([[1, 2, 3, 10],
                   [4, 5, 6, 20],
                   [7, 8, 9, 30]])

matriz

In [ ]:
print(matriz)

In [ ]:
matriz.flatten()

In [ ]:
matriz.reshape(6, 2)

In [ ]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty(shape = (5, 5), dtype = "float")

print(empty)

In [ ]:
# Inicializa una matriz de 1's.

ones = np.ones(shape = (5, 5), dtype = "int8")

print(ones)

In [ ]:
# Inicializa una matriz de 0's.

zeros = np.zeros(shape = (5, 5), dtype = "int8")

print(zeros)

In [ ]:
# Matriz identidad

np.eye(5)

In [ ]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(1, 12, 16)

print(linspace)

### Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [ ]:
matriz = np.array([[1, 0, 0, 0, 0],
                   [0, 0, 2, 0, 0],
                   [1, 1, 0, 0, 1],
                   [2, 1, 1, 1, 0],
                   [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [ ]:
# Hacer

matriz[4][1]

np.int64(2)

In [ ]:
# Es igual que hacer

matriz[4, 1]

In [ ]:
# Slicing
matriz[1:4, 1:4]

In [ ]:
# Slicing + Indexing

matriz[[1, 3], [2, 4]]

### Operaciones con Arrays

In [ ]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

In [ ]:
# Suma

A + B

In [ ]:
# Resta
A - B

In [ ]:
# Multiplicación por escalar

A * 5

In [ ]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

In [ ]:
# División por escalar

A / 5

In [ ]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

In [ ]:
print(A)
print("-"*20)
print(B)

#### Concatenar

In [ ]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0)

In [ ]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1)

### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                                                                                 |
|**`np.random.RandomState(n)`**      | Genera una semilla.                                                                                                                                 |

In [ ]:
np.random.random(size = (5, 5))

array([[0.62041924, 0.44375034, 0.4753541 , 0.97863256, 0.97552646],
       [0.92177358, 0.05375848, 0.6191526 , 0.36543618, 0.19110851],
       [0.62849963, 0.04255723, 0.9629026 , 0.83248618, 0.95662262],
       [0.47729399, 0.58293257, 0.83639951, 0.3489424 , 0.02573393],
       [0.89315123, 0.57397738, 0.10270953, 0.55935064, 0.63806712]])

In [ ]:
print(np.random.random())

print("-"*30)

print(np.random.random(5))

0.8609386353162439
------------------------------
[0.9486075  0.87993213 0.43865342 0.61511428 0.28462469]


In [ ]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(2, 3))

0.7486636198505473
------------------------------
[[0.90 0.08 0.55]
 [0.58 0.96 0.29]]


In [ ]:
print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

-0.8594045325653367
------------------------------
[[-2.14513959  1.2007306  -2.77458132]
 [-0.33641666 -0.45733671 -0.48545877]]


In [ ]:
print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = (5, 5)))

6
------------------------------
[[2 6 2 5 1]
 [7 6 8 5 8]
 [5 8 8 3 6]
 [7 5 1 1 3]
 [5 9 3 4 6]]


In [ ]:
print(np.random.choice(a    = ["a", "e", "i", "o", "u"],
                       size = 10,
                       p    = [0.6, 0.1, 0.1, 0.1, 0.1]))

['a' 'o' 'a' 'o' 'a' 'o' 'a' 'o' 'a' 'u']


In [ ]:
for i in range(5):

    np.random.seed(0)

    print(np.random.randn())

1.764052345967664
1.764052345967664
1.764052345967664
1.764052345967664
1.764052345967664


In [ ]:
for i in range(4):

    rs = np.random.RandomState(2)

    print(rs.rand())
    print(rs.randint(0, 10))

    print(np.random.randn()) # No usa rs

    print("-"*30)

0.43599490214200376
8
0.4001572083672233
------------------------------
0.43599490214200376
8
0.9787379841057392
------------------------------
0.43599490214200376
8
2.240893199201458
------------------------------
0.43599490214200376
8
1.8675579901499675
------------------------------


In [ ]:
np.random.seed(0)

for i in range(4):

    print(np.random.rand())
    print(np.random.randint(0, 10))
    print(np.random.randn())
    print("-"*30)

0.5488135039273248
5
0.11849646073740812
------------------------------
0.8472517387841254
3
0.11396779497090676
------------------------------
0.6458941130666561
4
-0.2913939760114335
------------------------------
0.2726562945801132
1
-0.13309028458966213
------------------------------


In [ ]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

np.set_printoptions(formatter = {"float" : lambda x: "{0:0.2f}".format(x)})

np.random.randn(6, 6)

array([[0.61, 0.92, 0.38, -1.10, 0.30, 1.33],
       [-0.69, -0.15, -0.44, 1.85, 0.67, 0.41],
       [-0.77, 0.54, -0.67, 0.03, -0.64, 0.68],
       [0.58, -0.21, 0.40, -1.09, -1.49, 0.44],
       [0.17, 0.64, 2.38, 0.94, -0.91, 1.12],
       [-1.32, -0.46, -0.07, 1.71, -0.74, -0.83]])

In [ ]:
np.random.randn(6, 6)

array([[-0.10, -0.66, 1.13, -1.08, -1.15, -0.44],
       [-0.50, 1.93, 0.95, 0.09, -1.23, 0.84],
       [-1.00, -1.54, 1.19, 0.32, 0.92, 0.32],
       [0.86, -0.65, -1.03, 0.68, -0.80, -0.69],
       [-0.46, 0.02, -0.35, -1.37, -0.64, -2.22],
       [0.63, -1.60, -1.10, 0.05, -0.74, 1.54]])

In [ ]:
np.empty((5, 5), dtype = "float64")

array([[0.62, 0.44, 0.48, 0.98, 0.98],
       [0.92, 0.05, 0.62, 0.37, 0.19],
       [0.63, 0.04, 0.96, 0.83, 0.96],
       [0.48, 0.58, 0.84, 0.35, 0.03],
       [0.89, 0.57, 0.10, 0.56, 0.64]])

In [ ]:
################################################################################################################################